import { BlockType } from '@aresrpg/aresrpg-world'

import { proc_items } from './world_conf.js'
import { schem_items } from './schematics_conf.js'

const temperate = {
  sea: {
    id: 0,
    x: 0,
    y: 0,
    type: BlockType.WATER,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 2,
  },
  sea_2: { x: 0.18, y: 0.05 },
  beach: {
    id: 2,
    x: 0.26,
    y: 0.21,
    type: BlockType.SAND,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 5,
  },
  cliff: {
    id: 3,
    x: 0.33,
    y: 0.23,
    type: BlockType.ROCK,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  cliff_2: { x: 0.48, y: 0.42 },
  lands: {
    id: 4,
    x: 0.48,
    y: 0.42,
    type: BlockType.GRASS,
    subtype: BlockType.MUD,
    entities: [proc_items.AppleTree_M],
    fadeIn: 0,
    fadeOut: 0.2,
  },
  mountains: {
    id: 5,
    x: 0.71,
    y: 0.52,
    type: BlockType.ROCK,
    subtype: BlockType.GRASS,
    entities: [schem_items.SpruceTree],
    mixratio: 0.1,
    fadeIn: 0,
    fadeOut: 25,
  },
  mountains_top: {
    id: 6,
    x: 0.9,
    y: 0.76,
    type: BlockType.SNOW,
    subtype: BlockType.ROCK,
    fadeIn: 0,
    fadeOut: 0,
  },
  mountains_top_2: { x: 0.95, y: 0.92 },
  mountains_top_3: { x: 1, y: 0.9 },
}

const artic = {
  sea: {
    id: 0,
    x: 0,
    y: 0,
    type: BlockType.WATER,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 1,
  },
  sea_2: { x: 0.18, y: 0.05 },
  beach: {
    id: 2,
    x: 0.26,
    y: 0.21,
    type: BlockType.ICE,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 3,
  },
  cliff: {
    id: 3,
    x: 0.33,
    y: 0.23,
    type: BlockType.SNOW,
    subtype: BlockType.ICE,
    mixratio: 0.25,
    fadeIn: 2,
    fadeOut: 10,
  },
  cliff_2: { x: 0.48, y: 0.42 },
  lands: {
    id: 4,
    x: 0.48,
    y: 0.42,
    type: BlockType.SNOW,
    subtype: BlockType.ICE,
    entities: [proc_items.PineTree_M],
    fadeIn: 1,
    fadeOut: 5,
  },
  mountains: {
    id: 5,
    x: 0.71,
    y: 0.45,
    type: BlockType.SNOW,
    subtype: BlockType.ROCK,
    entities: [schem_items.SpruceTree],
    fadeIn: 5,
    fadeOut: 30,
  },
  mountains_top: {
    id: 6,
    x: 0.9,
    y: 0.65,
    type: BlockType.SNOW,
    subtype: BlockType.ROCK,
    fadeIn: 10,
    fadeOut: 40,
  },
  mountains_top_2: { x: 0.95, y: 0.7 },
  mountains_top_3: { x: 1, y: 0.7 },
}

const desert = {
  sea_start: {
    id: 0,
    x: 0,
    y: 0,
    type: BlockType.WATER,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 1,
  },
  sea_end: { x: 0.18, y: 0.05 },
  beach: {
    id: 2,
    x: 0.26,
    y: 0.21,
    type: BlockType.SAND,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 3,
  },
  cliff: {
    id: 3,
    x: 0.33,
    y: 0.23,
    type: BlockType.ROCK,
    subtype: BlockType.SAND,
    fadeIn: 2,
    fadeOut: 10,
  },
  dunes: {
    id: 4,
    x: 0.48,
    y: 0.42,
    type: BlockType.SAND,
    subtype: BlockType.NONE,
    fadeIn: 1,
    fadeOut: 10,
  },
  dunes_end: {
    id: 5,
    x: 1,
    y: 0.52,
    type: BlockType.SAND,
    subtype: BlockType.ROCK,
    fadeIn: 5,
    fadeOut: 25,
  },
}

export const biome_mapping_conf = { temperate, desert, artic }
