import { BLOCKS } from '../blocks.js'

const rocks_icepic_1 = {
  'rocks/ARCTIC_ICEPIC_G1': 1,
  'rocks/ARCTIC_ICEPIC_G2': 1,
  'rocks/ARCTIC_ICEPIC_G3': 1,
  'rocks/ARCTIC_ICEPIC_G4': 1,
  'rocks/ARCTIC_ICEPIC_G5': 1,
  'rocks/ARCTIC_ICEPIC_G6': 1,
}

export default {
  abyss: {
    x: 0,
    y: 0,
    type: BLOCKS.COLD_WATER,
    subtype: BLOCKS.DARKER_ICE,
    fadeIn: 0,
    fadeOut: 0,
  },
  shore: {
    x: 0.2,
    y: 0.1,
    type: BLOCKS.DARK_ICE,
    subtype: BLOCKS.DARKER_ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      void: 50,
    },
  },
  floe: {
    x: 0.21,
    y: 0.302,
    type: BLOCKS.ICE,
    subtype: BLOCKS.DARK_ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 8,
      'rocks/ARCTIC_ICEPIC_G2': 8,
      'rocks/ARCTIC_ICEPIC_G3': 8,
      'rocks/ARCTIC_ICEPIC_G4': 8,
      'rocks/ARCTIC_ICEPIC_G5': 8,
      'rocks/ARCTIC_ICEPIC_G6': 8,
      'rocks/ARCTIC_BIG_ROCK_G1': 1,
      'rocks/ARCTIC_BIG_ROCK_G2': 1,
      'rocks/ARCTIC_BIG_ROCK_G3': 1,
      void: 150,
    },
  },
  land_stone: {
    x: 0.55,
    y: 0.33,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      ...rocks_icepic_1,
      void: 60,
    },
  },
  land: {
    x: 0.58,
    y: 0.33,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 60,
    },
  },
  cliff_up: {
    x: 0.65,
    y: 0.4,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TAIGA_TREE_G1': 10,
      'trees/TAIGA_TREE_G2': 10,
      'trees/TAIGA_TREE_G3': 10,
      'rocks/ARCTIC_BIG_ROCK_G1': 1,
      'rocks/ARCTIC_BIG_ROCK_G2': 1,
      'rocks/ARCTIC_BIG_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 100,
    },
  },
  plaine: {
    x: 0.75,
    y: 0.38,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TAIGA_TREE_G1': 10,
      'trees/TAIGA_TREE_G2': 10,
      'trees/TAIGA_TREE_G3': 10,
      'rocks/ARCTIC_BIG_ROCK_G1': 1,
      'rocks/ARCTIC_BIG_ROCK_G2': 1,
      'rocks/ARCTIC_BIG_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 80,
    },
  },
  cliff_up_2: {
    x: 1,
    y: 0.48,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TAIGA_TREE_G1': 10,
      'trees/TAIGA_TREE_G2': 10,
      'trees/TAIGA_TREE_G3': 10,
      'rocks/ARCTIC_BIG_ROCK_G1': 1,
      'rocks/ARCTIC_BIG_ROCK_G2': 1,
      'rocks/ARCTIC_BIG_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 60,
    },
  },
}
