import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  Oasis: {
    x: 0,
    y: 0,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  Beach_start: {
    x: 14,
    y: 0.305,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  Beach: {
    x: 0.15,
    y: 0.305,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      void: 1,
    },
  },
  plaine: {
    x: 0.2,
    y: 0.305,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 50,
    },
  },
  Cliff_start: {
    x: 0.24,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 70,
    },
  },
  Cliff_up: {
    x: 0.3,
    y: 0.35,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      'trees/DESERT_DEAD_TREE_G1': 2,
      'trees/DESERT_DEAD_TREE_G2': 2,
      'trees/DESERT_DEAD_TREE_G3': 2,
      'trees/DESERT_DEAD_TREE_G4': 2,
      void: 50,
    },
  },
  Cliff_up_2: {
    x: 0.4,
    y: 0.37,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/DESERT_CACTUS_G1': 1,
      'trees/DESERT_CACTUS_G2': 1,
      'trees/DESERT_CACTUS_G3': 1,
      'trees/DESERT_CACTUS_G4': 1,
      'trees/DESERT_DEAD_TREE_G1': 1,
      'trees/DESERT_DEAD_TREE_G2': 1,
      'trees/DESERT_DEAD_TREE_G3': 1,
      'trees/DESERT_DEAD_TREE_G4': 1,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 70,
    },
  },
  plateau: {
    x: 0.5,
    y: 0.38,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/DESERT_CACTUS_G1': 3,
      'trees/DESERT_CACTUS_G2': 3,
      'trees/DESERT_CACTUS_G3': 3,
      'trees/DESERT_CACTUS_G4': 3,
      'trees/DESERT_DEAD_TREE_G1': 1,
      'trees/DESERT_DEAD_TREE_G2': 1,
      'trees/DESERT_DEAD_TREE_G3': 1,
      'trees/DESERT_DEAD_TREE_G4': 1,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 70,
    },
  },
  Cliff_start_2: {
    x: 0.68,
    y: 0.38,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/DESERT_CACTUS_G1': 3,
      'trees/DESERT_CACTUS_G2': 3,
      'trees/DESERT_CACTUS_G3': 3,
      'trees/DESERT_CACTUS_G4': 3,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 70,
    },
  },
  Cliff_up_3: {
    x: 0.78,
    y: 0.45,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/DESERT_CACTUS_G1': 3,
      'trees/DESERT_CACTUS_G2': 3,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 70,
    },
  },
  end: {
    x: 0.7,
    y: 0.38,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/DESERT_CACTUS_G1': 3,
      'trees/DESERT_CACTUS_G2': 3,
      'trees/DESERT_CACTUS_G3': 3,
      'trees/DESERT_CACTUS_G4': 3,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 70,
    },
  },
}
