import { BLOCKS } from '../blocks.js'

export default {
  1: {
    x: 0,
    y: 0.23,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  2: {
    x: 0.05,
    y: 0.24,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  3: {
    x: 0.09,
    y: 0.26,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  4: {
    x: 0.13,
    y: 0.27,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  5: {
    x: 0.15,
    y: 0.28,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  6: {
    x: 0.18,
    y: 0.3,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  7: {
    x: 0.2,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  8: {
    x: 0.25,
    y: 0.33,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  9: {
    x: 0.29,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  10: {
    x: 0.33,
    y: 0.33,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  11: {
    x: 0.38,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  12: {
    x: 0.44,
    y: 0.33,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  13: {
    x: 0.5,
    y: 0.38,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  14: {
    x: 0.54,
    y: 0.42,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  15: {
    x: 0.56,
    y: 0.43,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  16: {
    x: 0.57,
    y: 0.45,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  17: {
    x: 0.59,
    y: 0.48,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  18: {
    x: 0.61,
    y: 0.51,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  19: {
    x: 0.65,
    y: 0.53,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  20: {
    x: 0.67,
    y: 0.52,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  21: {
    x: 0.68,
    y: 0.51,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  22: {
    x: 0.69,
    y: 0.44,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  23: {
    x: 0.7,
    y: 0.39,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  24: {
    x: 0.71,
    y: 0.35,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  25: {
    x: 0.74,
    y: 0.34,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  26: {
    x: 0.76,
    y: 0.35,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  27: {
    x: 0.77,
    y: 0.41,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  28: {
    x: 0.78,
    y: 0.49,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  29: {
    x: 0.79,
    y: 0.52,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  30: {
    x: 0.81,
    y: 0.53,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  31: {
    x: 0.83,
    y: 0.53,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
}
