import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  flat: {
    x: 0,
    y: 0.35,
    type: BlockType.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/DESERT_TREE_G1': 3,
      'trees/DESERT_TREE_G2': 3,
      'trees/DESERT_TREE_G3': 3,
      'trees/DESERT_TREE_G4': 3,
      'trees/DESERT_TREE_G5': 3,
      'trees/DESERT_TREE_G6': 3,
      'trees/DESERT_DEAD_TREE_G1': 1,
      'trees/DESERT_DEAD_TREE_G2': 1,
      'trees/DESERT_DEAD_TREE_G3': 1,
      'trees/DESERT_DEAD_TREE_G4': 1,
      // 'rocks/DESERT_BIG_ROCK_G1': 1,
      // 'rocks/DESERT_BIG_ROCK_G2': 1,
      // 'rocks/DESERT_BIG_ROCK_G3': 1,
      // 'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 100,
    },
  },
  Up_flat: {
    x: 0.2,
    y: 0.35,
    type: BlockType.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/DESERT_TREE_G1': 3,
      'trees/DESERT_TREE_G2': 3,
      'trees/DESERT_TREE_G3': 3,
      'trees/DESERT_TREE_G4': 3,
      'trees/DESERT_TREE_G5': 3,
      'trees/DESERT_TREE_G6': 3,
      // 'rocks/DESERT_BIG_ROCK_G1': 1,
      // 'rocks/DESERT_BIG_ROCK_G2': 1,
      // 'rocks/DESERT_BIG_ROCK_G3': 1,
      // 'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 100,
    },
  },
  down_flat: {
    x: 0.4,
    y: 0.38,
    type: BlockType.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/DESERT_TREE_G1': 1,
      // 'trees/DESERT_TREE_G2': 1,
      // 'trees/DESERT_TREE_G3': 1,
      // 'trees/DESERT_TREE_G4': 1,
      // 'trees/DESERT_TREE_G5': 1,
      // 'trees/DESERT_TREE_G6': 1,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 100,
    },
  },
  low_up: {
    x: 0.6,
    y: 0.35,
    type: BlockType.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/DESERT_TREE_G1': 1,
      // 'trees/DESERT_TREE_G2': 1,
      // 'trees/DESERT_TREE_G3': 1,
      // 'trees/DESERT_TREE_G4': 1,
      // 'trees/DESERT_TREE_G5': 1,
      // 'trees/DESERT_TREE_G6': 1,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 100,
    },
  },
  low_down: {
    x: 0.8,
    y: 0.6,
    type: BlockType.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/DESERT_TREE_G1': 1,
      // 'trees/DESERT_TREE_G2': 1,
      // 'trees/DESERT_TREE_G3': 1,
      // 'trees/DESERT_TREE_G4': 1,
      // 'trees/DESERT_TREE_G5': 1,
      // 'trees/DESERT_TREE_G6': 1,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 100,
    },
  },
  end: {
    x: 0.95,
    y: 0.8,
    type: BlockType.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/DESERT_TREE_G1': 1,
      // 'trees/DESERT_TREE_G2': 1,
      // 'trees/DESERT_TREE_G3': 1,
      // 'trees/DESERT_TREE_G4': 1,
      // 'trees/DESERT_TREE_G5': 1,
      // 'trees/DESERT_TREE_G6': 1,
      'rocks/DESERT_BIG_ROCK_G1': 1,
      'rocks/DESERT_BIG_ROCK_G2': 1,
      'rocks/DESERT_BIG_ROCK_G3': 1,
      'rocks/DESERT_BIG_ROCK_G4': 1,
      void: 100,
    },
  },
}
