import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  Water: {
    x: 0,
    y: 0.1,
    type: BLOCKS.ICE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ICE_G1': 100,
    },
  },
  aa: {
    x: 0.25,
    y: 0.3,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
  },
  a: {
    x: 0.25,
    y: 0.4,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
  },
  b: {
    x: 0.3,
    y: 0.4,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_ROCK_G1': 6,
      'rocks/GLACIER_ROCK_G2': 6,
      'rocks/GLACIER_ROCK_G3': 6,
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      void: 20,
    },
  },
  cs: {
    x: 0.7,
    y: 0.42,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_ROCK_G1': 6,
      'rocks/GLACIER_ROCK_G2': 6,
      'rocks/GLACIER_ROCK_G3': 6,
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      void: 20,
    },
  },
  c: {
    x: 0.75,
    y: 0.5,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_ROCK_G1': 6,
      'rocks/GLACIER_ROCK_G2': 6,
      'rocks/GLACIER_ROCK_G3': 6,
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      void: 20,
    },
  },
  d: {
    x: 0.85,
    y: 0.7,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_ROCK_G1': 6,
      'rocks/GLACIER_ROCK_G2': 6,
      'rocks/GLACIER_ROCK_G3': 6,
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      void: 20,
    },
  },
  e: {
    x: 0.9,
    y: 0.8,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_ROCK_G1': 6,
      'rocks/GLACIER_ROCK_G2': 6,
      'rocks/GLACIER_ROCK_G3': 6,
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      void: 20,
    },
  },
  f: {
    x: 1,
    y: 0.9,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_ROCK_G1': 6,
      'rocks/GLACIER_ROCK_G2': 6,
      'rocks/GLACIER_ROCK_G3': 6,
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      void: 20,
    },
  },
}
