import { BLOCKS } from '../blocks.js'

export default {
  1: {
    x: 0,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  2: {
    x: 0.01,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  3: {
    x: 0.02,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  4: {
    x: 0.03,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  5: {
    x: 0.04,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  6: {
    x: 0.05,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  7: {
    x: 0.06,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  8: {
    x: 0.07,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  9: {
    x: 0.08,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  10: {
    x: 0.09,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  11: {
    x: 0.1,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  12: {
    x: 0.11,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  13: {
    x: 0.12,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  14: {
    x: 0.13,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  15: {
    x: 0.14,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  16: {
    x: 0.15,
    y: 0.35,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  17: {
    x: 0.17,
    y: 0.41,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  18: {
    x: 0.22,
    y: 0.45,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  19: {
    x: 0.24,
    y: 0.52,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  20: {
    x: 0.29,
    y: 0.55,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  21: {
    x: 0.3,
    y: 0.6,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  22: {
    x: 0.35,
    y: 0.65,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  23: {
    x: 0.37,
    y: 0.7,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  24: {
    x: 0.39,
    y: 0.81,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  25: {
    x: 0.43,
    y: 0.86,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  26: {
    x: 0.46,
    y: 0.83,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  27: {
    x: 0.48,
    y: 0.62,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  28: {
    x: 0.5,
    y: 0.61,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  29: {
    x: 0.52,
    y: 0.62,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  30: {
    x: 0.54,
    y: 0.83,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  31: {
    x: 0.57,
    y: 0.86,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  32: {
    x: 0.61,
    y: 0.81,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  33: {
    x: 0.63,
    y: 0.7,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  34: {
    x: 0.65,
    y: 0.65,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  35: {
    x: 0.7,
    y: 0.6,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  36: {
    x: 0.71,
    y: 0.55,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  37: {
    x: 0.76,
    y: 0.52,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  38: {
    x: 0.78,
    y: 0.45,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  39: {
    x: 0.83,
    y: 0.41,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  40: {
    x: 0.85,
    y: 0.35,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  41: {
    x: 0.86,
    y: 0.35,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/GLACIER_BIG_ROCK_G1': 1,
      'rocks/GLACIER_BIG_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G1': 1,
      'rocks/GLACIER_ROCK_G2': 1,
      'rocks/GLACIER_ROCK_G3': 1,
      void: 20,
    },
  },
  42: {
    x: 0.87,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  43: {
    x: 0.88,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  44: {
    x: 0.89,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  45: {
    x: 0.9,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  46: {
    x: 0.91,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  47: {
    x: 0.92,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  48: {
    x: 0.93,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  49: {
    x: 0.94,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  50: {
    x: 0.95,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  51: {
    x: 0.96,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  52: {
    x: 0.97,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  53: {
    x: 0.98,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  54: {
    x: 0.99,
    y: 0.34,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
  55: {
    x: 1,
    y: 0.35,
    type: BLOCKS.ICE,
    subtype: BLOCKS.ICE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/ARCTIC_ICEPIC_G1': 1,
      'rocks/ARCTIC_ICEPIC_G2': 1,
      'rocks/ARCTIC_ICEPIC_G3': 1,
      'rocks/ARCTIC_ICEPIC_G4': 1,
      'rocks/ARCTIC_ICEPIC_G5': 1,
      'rocks/ARCTIC_ICEPIC_G6': 1,
      void: 20,
    },
  },
}
