import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  Up_flat: {
    x: 0,
    y: 0.35,
    type: BlockType.GRASS,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/GRASSLAND_TREE_G1': 5,
      'trees/GRASSLAND_TREE_G2': 5,
      'trees/GRASSLAND_TREE_G3': 5,
      'trees/GRASSLAND_TREE_G4': 5,
      'trees/GRASSLAND_BIG_TREE_G1': 5,
      'trees/GRASSLAND_BIG_TREE_G2': 5,
      'rocks/GRASSLAND_ROCK_G1': 1,
      'rocks/GRASSLAND_ROCK_G2': 1,
      'rocks/GRASSLAND_ROCK_G3': 1,
      'rocks/GRASSLAND_ROCK_G4': 1,
      'rocks/GRASSLAND_ROCK_G5': 1,
      'rocks/GRASSLAND_ROCK_G6': 1,
      void: 100,
    },
  },
  down_flat: {
    x: 0.2,
    y: 0.35,
    type: BlockType.GRASS,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/GRASSLAND_TREE_G1': 5,
      'trees/GRASSLAND_TREE_G2': 5,
      'trees/GRASSLAND_TREE_G3': 5,
      'trees/GRASSLAND_TREE_G4': 5,
      'trees/GRASSLAND_BIG_TREE_G1': 5,
      'trees/GRASSLAND_BIG_TREE_G2': 5,
      'rocks/GRASSLAND_ROCK_G1': 1,
      'rocks/GRASSLAND_ROCK_G2': 1,
      'rocks/GRASSLAND_ROCK_G3': 1,
      'rocks/GRASSLAND_ROCK_G4': 1,
      'rocks/GRASSLAND_ROCK_G5': 1,
      'rocks/GRASSLAND_ROCK_G6': 1,
      void: 100,
    },
  },
  flat: {
    x: 0.4,
    y: 0.4,
    type: BlockType.GRASS,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/GRASSLAND_TREE_G1': 5,
      'trees/GRASSLAND_TREE_G2': 5,
      'trees/GRASSLAND_TREE_G3': 5,
      'trees/GRASSLAND_TREE_G4': 5,
      'trees/GRASSLAND_BIG_TREE_G1': 5,
      'trees/GRASSLAND_BIG_TREE_G2': 5,
      'rocks/GRASSLAND_ROCK_G1': 1,
      'rocks/GRASSLAND_ROCK_G2': 1,
      'rocks/GRASSLAND_ROCK_G3': 1,
      'rocks/GRASSLAND_ROCK_G4': 1,
      'rocks/GRASSLAND_ROCK_G5': 1,
      'rocks/GRASSLAND_ROCK_G6': 1,
      void: 100,
    },
  },
  Up_flat2: {
    x: 0.6,
    y: 0.35,
    type: BlockType.GRASS,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/GRASSLAND_TREE_G1': 5,
      'trees/GRASSLAND_TREE_G2': 5,
      'trees/GRASSLAND_TREE_G3': 5,
      'trees/GRASSLAND_TREE_G4': 5,
      'trees/GRASSLAND_BIG_TREE_G1': 5,
      'trees/GRASSLAND_BIG_TREE_G2': 5,
      'rocks/GRASSLAND_ROCK_G1': 1,
      'rocks/GRASSLAND_ROCK_G2': 1,
      'rocks/GRASSLAND_ROCK_G3': 1,
      'rocks/GRASSLAND_ROCK_G4': 1,
      'rocks/GRASSLAND_ROCK_G5': 1,
      'rocks/GRASSLAND_ROCK_G6': 1,
      void: 100,
    },
  },
  down_flat2: {
    x: 0.8,
    y: 0.45,
    type: BlockType.GRASS,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/GRASSLAND_TREE_G1': 5,
      'trees/GRASSLAND_TREE_G2': 5,
      'trees/GRASSLAND_TREE_G3': 5,
      'trees/GRASSLAND_TREE_G4': 5,
      'trees/GRASSLAND_BIG_TREE_G1': 5,
      'trees/GRASSLAND_BIG_TREE_G2': 5,
      'rocks/GRASSLAND_ROCK_G1': 1,
      'rocks/GRASSLAND_ROCK_G2': 1,
      'rocks/GRASSLAND_ROCK_G3': 1,
      'rocks/GRASSLAND_ROCK_G4': 1,
      'rocks/GRASSLAND_ROCK_G5': 1,
      'rocks/GRASSLAND_ROCK_G6': 1,
      void: 100,
    },
  },
  end: {
    x: 1,
    y: 0.35,
    type: BlockType.GRASS,
    subtype: BlockType.NONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/GRASSLAND_TREE_G1': 5,
      'trees/GRASSLAND_TREE_G2': 5,
      'trees/GRASSLAND_TREE_G3': 5,
      'trees/GRASSLAND_TREE_G4': 5,
      'trees/GRASSLAND_BIG_TREE_G1': 5,
      'trees/GRASSLAND_BIG_TREE_G2': 5,
      'rocks/GRASSLAND_ROCK_G1': 1,
      'rocks/GRASSLAND_ROCK_G2': 1,
      'rocks/GRASSLAND_ROCK_G3': 1,
      'rocks/GRASSLAND_ROCK_G4': 1,
      'rocks/GRASSLAND_ROCK_G5': 1,
      'rocks/GRASSLAND_ROCK_G6': 1,
      void: 100,
    },
  },
}
