import { BLOCKS } from '../blocks.js'

export default {
  plaine: {
    x: 0,
    y: 0.31,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/SCORCHED_ROCK_DOME_G1': 5,
      'rocks/SCORCHED_ROCK_DOME_G2': 5,
      'rocks/SCORCHED_ROCK_DOME_G3': 5,
      'rocks/SCORCHED_ROCK_DOME_G4': 5,
      'rocks/SCORCHED_ROCK_DOME_G5': 5,
      'rocks/SCORCHED_ROCK_LAVA_G1': 5,
      'rocks/SCORCHED_ROCK_LAVA_G2': 5,
      'rocks/SCORCHED_ROCK_LAVA_G3': 1,
      'rocks/SCORCHED_ROCK_LAVA_G4': 1,
      'rocks/SCORCHED_ROCK_LITTLE_G1': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G2': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G3': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G4': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G5': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G6': 5,
      void: 40,
    },
  },
  up: {
    x: 0.24,
    y: 0.31,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/SCORCHED_ROCK_DOME_G1': 5,
      'rocks/SCORCHED_ROCK_DOME_G2': 5,
      'rocks/SCORCHED_ROCK_DOME_G3': 5,
      'rocks/SCORCHED_ROCK_DOME_G4': 5,
      'rocks/SCORCHED_ROCK_DOME_G5': 5,
      'rocks/SCORCHED_ROCK_LAVA_G1': 5,
      'rocks/SCORCHED_ROCK_LAVA_G2': 5,
      'rocks/SCORCHED_ROCK_LAVA_G3': 1,
      'rocks/SCORCHED_ROCK_LAVA_G4': 1,
      'rocks/SCORCHED_ROCK_LITTLE_G1': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G2': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G3': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G4': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G5': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G6': 5,
      void: 40,
    },
  },
  down: {
    x: 0.28,
    y: 0.33,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/SCORCHED_ROCK_DOME_G1': 5,
      'rocks/SCORCHED_ROCK_DOME_G2': 5,
      'rocks/SCORCHED_ROCK_DOME_G3': 5,
      'rocks/SCORCHED_ROCK_DOME_G4': 5,
      'rocks/SCORCHED_ROCK_DOME_G5': 5,
      'rocks/SCORCHED_ROCK_LAVA_G1': 5,
      'rocks/SCORCHED_ROCK_LAVA_G2': 5,
      'rocks/SCORCHED_ROCK_LAVA_G3': 1,
      'rocks/SCORCHED_ROCK_LAVA_G4': 1,
      'rocks/SCORCHED_ROCK_LITTLE_G1': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G2': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G3': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G4': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G5': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G6': 5,
      void: 100,
    },
  },
  Lava_start: {
    x: 0.32,
    y: 0.31,
    type: BLOCKS.RED_CONCRETE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  up_2: {
    x: 0.36,
    y: 0.31,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/SCORCHED_ROCK_DOME_G1': 5,
      'rocks/SCORCHED_ROCK_DOME_G2': 5,
      'rocks/SCORCHED_ROCK_DOME_G3': 5,
      'rocks/SCORCHED_ROCK_DOME_G4': 5,
      'rocks/SCORCHED_ROCK_DOME_G5': 5,
      'rocks/SCORCHED_ROCK_LAVA_G1': 5,
      'rocks/SCORCHED_ROCK_LAVA_G2': 5,
      'rocks/SCORCHED_ROCK_LAVA_G3': 1,
      'rocks/SCORCHED_ROCK_LAVA_G4': 1,
      'rocks/SCORCHED_ROCK_LITTLE_G1': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G2': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G3': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G4': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G5': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G6': 5,
      void: 100,
    },
  },
  down_2: {
    x: 0.4,
    y: 0.33,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/SCORCHED_ROCK_DOME_G1': 5,
      'rocks/SCORCHED_ROCK_DOME_G2': 5,
      'rocks/SCORCHED_ROCK_DOME_G3': 5,
      'rocks/SCORCHED_ROCK_DOME_G4': 5,
      'rocks/SCORCHED_ROCK_DOME_G5': 5,
      'rocks/SCORCHED_ROCK_LAVA_G1': 5,
      'rocks/SCORCHED_ROCK_LAVA_G2': 5,
      'rocks/SCORCHED_ROCK_LAVA_G3': 1,
      'rocks/SCORCHED_ROCK_LAVA_G4': 1,
      'rocks/SCORCHED_ROCK_LITTLE_G1': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G2': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G3': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G4': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G5': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G6': 5,
      void: 40,
    },
  },
  Cliff_start: {
    x: 0.6,
    y: 0.31,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/SCORCHED_ROCK_DOME_G1': 5,
      'rocks/SCORCHED_ROCK_DOME_G2': 5,
      'rocks/SCORCHED_ROCK_DOME_G3': 5,
      'rocks/SCORCHED_ROCK_DOME_G4': 5,
      'rocks/SCORCHED_ROCK_DOME_G5': 5,
      'rocks/SCORCHED_ROCK_LAVA_G1': 5,
      'rocks/SCORCHED_ROCK_LAVA_G2': 5,
      'rocks/SCORCHED_ROCK_LAVA_G3': 1,
      'rocks/SCORCHED_ROCK_LAVA_G4': 1,
      'rocks/SCORCHED_ROCK_LITTLE_G1': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G2': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G3': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G4': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G5': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G6': 5,
      void: 40,
    },
  },
  Cliff: {
    x: 0.64,
    y: 0.4,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  Cliff_down: {
    x: 0.7,
    y: 0.38,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/SCORCHED_ROCK_DOME_G1': 5,
      'rocks/SCORCHED_ROCK_DOME_G2': 5,
      'rocks/SCORCHED_ROCK_DOME_G3': 5,
      'rocks/SCORCHED_ROCK_DOME_G4': 5,
      'rocks/SCORCHED_ROCK_DOME_G5': 5,
      'rocks/SCORCHED_ROCK_LAVA_G1': 5,
      'rocks/SCORCHED_ROCK_LAVA_G2': 5,
      'rocks/SCORCHED_ROCK_LAVA_G3': 1,
      'rocks/SCORCHED_ROCK_LAVA_G4': 1,
      'rocks/SCORCHED_ROCK_LITTLE_G1': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G2': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G3': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G4': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G5': 5,
      'rocks/SCORCHED_ROCK_LITTLE_G6': 5,
      void: 40,
    },
  },
  Cliff_2: {
    x: 0.8,
    y: 0.6,
    type: BLOCKS.BLACKSTONE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  Cliff_lava: {
    x: 0.85,
    y: 0.52,
    type: BLOCKS.RED_CONCRETE,
    subtype: BLOCKS.BLACKSTONE,
    fadeIn: 0,
    fadeOut: 0,
  },
}
