import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  Water: {
    x: 0,
    y: 0,
    type: BLOCKS.MUD,
    subtype: BlockType.NONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  Rive_Mud_up: {
    x: 0.1,
    y: 0.1,
    type: BLOCKS.MUD,
    subtype: BLOCKS.MUD,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  Plateau_up: {
    x: 0.15,
    y: 0.305,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  Plateau_down_1: {
    x: 0.2,
    y: 0.31,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 30,
    },
  },
  Rive_Mud_down_1: {
    x: 0.25,
    y: 0.305,
    type: BLOCKS.MUD,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  Water_1: {
    x: 0.32,
    y: 0.3,
    type: BLOCKS.MUD,
    subtype: BlockType.NONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  Rive_Mud_up_1: {
    x: 0.4,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  Plateau_up_1: {
    x: 0.47,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  Plateau_down_2: {
    x: 0.52,
    y: 0.315,
    type: BLOCKS.MUD,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  Rive_Mud_down_2: {
    x: 0.57,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  Water_2: {
    x: 0.62,
    y: 0.3,
    type: BLOCKS.MUD,
    subtype: BlockType.NONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  Rive_Mud_up_2: {
    x: 0.7,
    y: 0.31,
    type: BLOCKS.MUD,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 2,
      'trees/SWAMP_NORMAL_TREE_G2': 2,
      'trees/SWAMP_NORMAL_TREE_G3': 2,
      'trees/SWAMP_NORMAL_TREE_G4': 2,
      'trees/SWAMP_NORMAL_TREE_G5': 2,
      'trees/SWAMP_NORMAL_TREE_G6': 2,
      'trees/SWAMP_DEAD_TREE_G1': 1,
      'trees/SWAMP_DEAD_TREE_G2': 1,
      'trees/SWAMP_DEAD_TREE_G3': 1,
      'trees/SWAMP_DEAD_TREE_G4': 1,
      void: 10,
    },
  },
  Plateau_up_2: {
    x: 0.77,
    y: 0.31,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 1,
      'trees/SWAMP_NORMAL_TREE_G2': 1,
      'trees/SWAMP_NORMAL_TREE_G3': 1,
      'trees/SWAMP_NORMAL_TREE_G4': 1,
      'trees/SWAMP_NORMAL_TREE_G5': 1,
      'trees/SWAMP_NORMAL_TREE_G6': 1,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 2,
      'trees/SWAMP_DEAD_TREE_G2': 2,
      'trees/SWAMP_DEAD_TREE_G3': 2,
      'trees/SWAMP_DEAD_TREE_G4': 2,
      void: 30,
    },
  },
  Water_3: {
    x: 0.85,
    y: 0.3,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 1,
      'trees/SWAMP_NORMAL_TREE_G2': 1,
      'trees/SWAMP_NORMAL_TREE_G3': 1,
      'trees/SWAMP_NORMAL_TREE_G4': 1,
      'trees/SWAMP_NORMAL_TREE_G5': 1,
      'trees/SWAMP_NORMAL_TREE_G6': 1,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 2,
      'trees/SWAMP_DEAD_TREE_G2': 2,
      'trees/SWAMP_DEAD_TREE_G3': 2,
      'trees/SWAMP_DEAD_TREE_G4': 2,
      void: 30,
    },
  },
  Plateau: {
    x: 0.92,
    y: 0.31,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/SWAMP_NORMAL_TREE_G1': 1,
      'trees/SWAMP_NORMAL_TREE_G2': 1,
      'trees/SWAMP_NORMAL_TREE_G3': 1,
      'trees/SWAMP_NORMAL_TREE_G4': 1,
      'trees/SWAMP_NORMAL_TREE_G5': 1,
      'trees/SWAMP_NORMAL_TREE_G6': 1,
      'trees/SWAMP_BIG_TREE_G1': 3,
      'trees/SWAMP_BIG_TREE_G2': 3,
      'trees/SWAMP_BIG_TREE_G3': 3,
      'trees/SWAMP_BIG_TREE_G4': 3,
      'trees/SWAMP_BIG_TREE_G5': 3,
      'trees/SWAMP_DEAD_TREE_G1': 2,
      'trees/SWAMP_DEAD_TREE_G2': 2,
      'trees/SWAMP_DEAD_TREE_G3': 2,
      'trees/SWAMP_DEAD_TREE_G4': 2,
      void: 20,
    },
  },
}
