import { BLOCKS } from '../blocks.js'

export default {
  flat: {
    x: 0,
    y: 0.4,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TAIGA_NORMAL_CHENE_G1': 1,
      'trees/TAIGA_NORMAL_CHENE_G2': 1,
      'trees/TAIGA_NORMAL_CHENE_G3': 1,
      'trees/TAIGA__TREE_G1': 1,
      'trees/TAIGA__TREE_G2': 1,
      'trees/TAIGA__TREE_G3': 1,
      void: 20,
    },
  },
  Up_flat: {
    x: 0.1,
    y: 0.4,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TAIGA_NORMAL_CHENE_G1': 1,
      'trees/TAIGA_NORMAL_CHENE_G2': 1,
      'trees/TAIGA_NORMAL_CHENE_G3': 1,
      'trees/TAIGA_TREE_G1': 1,
      'trees/TAIGA_TREE_G2': 1,
      'trees/TAIGA_TREE_G3': 1,
      void: 20,
    },
  },
  down_flat: {
    x: 0.2,
    y: 0.35,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TAIGA_NORMAL_CHENE_G1': 1,
      'trees/TAIGA_NORMAL_CHENE_G2': 1,
      'trees/TAIGA_NORMAL_CHENE_G3': 1,
      'trees/TAIGA_TREE_G1': 1,
      'trees/TAIGA_TREE_G2': 1,
      'trees/TAIGA_TREE_G3': 1,
      void: 20,
    },
  },
  Cliff: {
    x: 0.28,
    y: 0.55,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 10,
    fadeOut: 10,
    flora: {
      'trees/TAIGA_NORMAL_SAPIN_G1': 1,
      'trees/TAIGA_NORMAL_SAPIN_G2': 1,
      'trees/TAIGA_NORMAL_SAPIN_G3': 1,
      'trees/TAIGA_NORMAL_SAPIN_G4': 1,
      'trees/TAIGA_NORMAL_SAPIN_G5': 1,
      'trees/TAIGA_NORMAL_SAPIN_G6': 1,
      void: 20,
    },
  },
  High_flat_snow: {
    x: 0.4,
    y: 0.56,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TAIGA_NORMAL_SAPIN_G1': 1,
      'trees/TAIGA_NORMAL_SAPIN_G2': 1,
      'trees/TAIGA_NORMAL_SAPIN_G3': 1,
      'trees/TAIGA_NORMAL_SAPIN_G4': 1,
      'trees/TAIGA_NORMAL_SAPIN_G5': 1,
      'trees/TAIGA_NORMAL_SAPIN_G6': 1,
      void: 20,
    },
  },
  Cliff_3: {
    x: 0.5,
    y: 0.58,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TAIGA_BIG_SAPIN_NEIGE_G1': 1,
      'trees/TAIGA_BIG_SAPIN_NEIGE_G2': 1,
      'trees/TAIGA_BIG_SAPIN_NEIGE_G3': 1,
      void: 20,
    },
  },
  High_flat_2: {
    x: 0.7,
    y: 0.64,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TAIGA_BIG_SAPIN_NEIGE_G1': 1,
      'trees/TAIGA_BIG_SAPIN_NEIGE_G2': 1,
      'trees/TAIGA_BIG_SAPIN_NEIGE_G3': 1,
      void: 20,
    },
  },
  end: {
    x: 0.8,
    y: 0.62,
    type: BLOCKS.SNOW,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TAIGA_HUGE_SAPIN_G1': 1,
      'trees/TAIGA_HUGE_SAPIN_G2': 1,
      'trees/TAIGA_HUGE_SAPIN_G3': 1,
      void: 20,
    },
  },
}
