import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  flat: {
    x: 0,
    y: 0.35,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.BROWN_GRASS,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/TAIGA_LITTLE_TREE_G1': 2,
      // 'trees/TAIGA_LITTLE_TREE_G2': 2,
      // 'trees/TAIGA_LITTLE_TREE_G3': 2,
      // 'trees/TAIGA_LITTLE_TREE_G4': 2,
      // 'trees/TAIGA_LITTLE_TREE_G5': 2,
      // 'trees/TAIGA_LITTLE_TREE_G6': 2,
      'trees/TAIGA_TREE_G1': 50,
      'trees/TAIGA_TREE_G2': 50,
      'trees/TAIGA_TREE_G3': 50,
      'trees/TAIGA_TREE_G4': 50,
      'trees/TAIGA_TREE_G5': 50,
      'trees/TAIGA_TREE_G6': 50,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 10,
    },
  },
  Up_flat: {
    x: 0.2,
    y: 0.35,
    type: BLOCKS.BROWN_GRASS,
    subtype: BLOCKS.BROWN_GRASS,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/TAIGA_LITTLE_TREE_G1': 2,
      // 'trees/TAIGA_LITTLE_TREE_G2': 2,
      // 'trees/TAIGA_LITTLE_TREE_G3': 2,
      // 'trees/TAIGA_LITTLE_TREE_G4': 2,
      // 'trees/TAIGA_LITTLE_TREE_G5': 2,
      // 'trees/TAIGA_LITTLE_TREE_G6': 2,
      'trees/TAIGA_TREE_G1': 50,
      'trees/TAIGA_TREE_G2': 50,
      'trees/TAIGA_TREE_G3': 50,
      'trees/TAIGA_TREE_G4': 50,
      'trees/TAIGA_TREE_G5': 50,
      'trees/TAIGA_TREE_G6': 50,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 10,
    },
  },
  down_flat: {
    x: 0.4,
    y: 0.4,
    type: BlockType.MUD,
    subtype: BLOCKS.BROWN_GRASS,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/TAIGA_LITTLE_TREE_G1': 2,
      // 'trees/TAIGA_LITTLE_TREE_G2': 2,
      // 'trees/TAIGA_LITTLE_TREE_G3': 2,
      // 'trees/TAIGA_LITTLE_TREE_G4': 2,
      // 'trees/TAIGA_LITTLE_TREE_G5': 2,
      // 'trees/TAIGA_LITTLE_TREE_G6': 2,
      'trees/TAIGA_TREE_G1': 50,
      'trees/TAIGA_TREE_G2': 50,
      'trees/TAIGA_TREE_G3': 50,
      'trees/TAIGA_TREE_G4': 50,
      'trees/TAIGA_TREE_G5': 50,
      'trees/TAIGA_TREE_G6': 50,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 10,
    },
  },
  low_up: {
    x: 0.6,
    y: 0.35,
    type: BlockType.GRASS,
    subtype: BLOCKS.BROWN_GRASS,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/TAIGA_LITTLE_TREE_G1': 2,
      // 'trees/TAIGA_LITTLE_TREE_G2': 2,
      // 'trees/TAIGA_LITTLE_TREE_G3': 2,
      // 'trees/TAIGA_LITTLE_TREE_G4': 2,
      // 'trees/TAIGA_LITTLE_TREE_G5': 2,
      // 'trees/TAIGA_LITTLE_TREE_G6': 2,
      'trees/TAIGA_TREE_G1': 50,
      'trees/TAIGA_TREE_G2': 50,
      'trees/TAIGA_TREE_G3': 50,
      'trees/TAIGA_TREE_G4': 50,
      'trees/TAIGA_TREE_G5': 50,
      'trees/TAIGA_TREE_G6': 50,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 10,
    },
  },
  low_down: {
    x: 0.8,
    y: 0.45,
    type: BlockType.GRASS,
    subtype: BLOCKS.BROWN_GRASS,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/TAIGA_LITTLE_TREE_G1': 2,
      // 'trees/TAIGA_LITTLE_TREE_G2': 2,
      // 'trees/TAIGA_LITTLE_TREE_G3': 2,
      // 'trees/TAIGA_LITTLE_TREE_G4': 2,
      // 'trees/TAIGA_LITTLE_TREE_G5': 2,
      // 'trees/TAIGA_LITTLE_TREE_G6': 2,
      'trees/TAIGA_TREE_G1': 50,
      'trees/TAIGA_TREE_G2': 50,
      'trees/TAIGA_TREE_G3': 50,
      'trees/TAIGA_TREE_G4': 50,
      'trees/TAIGA_TREE_G5': 50,
      'trees/TAIGA_TREE_G6': 50,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 10,
    },
  },
  end: {
    x: 0.95,
    y: 0.35,
    type: BlockType.GRASS,
    subtype: BLOCKS.BROWN_GRASS,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      // 'trees/TAIGA_LITTLE_TREE_G1': 2,
      // 'trees/TAIGA_LITTLE_TREE_G2': 2,
      // 'trees/TAIGA_LITTLE_TREE_G3': 2,
      // 'trees/TAIGA_LITTLE_TREE_G4': 2,
      // 'trees/TAIGA_LITTLE_TREE_G5': 2,
      // 'trees/TAIGA_LITTLE_TREE_G6': 2,
      'trees/TAIGA_TREE_G1': 50,
      'trees/TAIGA_TREE_G2': 50,
      'trees/TAIGA_TREE_G3': 50,
      'trees/TAIGA_TREE_G4': 50,
      'trees/TAIGA_TREE_G5': 50,
      'trees/TAIGA_TREE_G6': 50,
      'rocks/TAIGA_ROCK_G1': 1,
      'rocks/TAIGA_ROCK_G2': 1,
      'rocks/TAIGA_ROCK_G3': 1,
      'rocks/TAIGA_ROCK_G4': 1,
      'rocks/TAIGA_ROCK_G5': 1,
      'rocks/TAIGA_ROCK_G6': 1,
      'rocks/TAIGA_ROCK_G7': 1,
      'rocks/TAIGA_ROCK_G8': 1,
      'rocks/TAIGA_ROCK_G9': 1,
      'rocks/TAIGA_ROCK_G10': 1,
      void: 10,
    },
  },
}
