import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  Plaine: {
    x: 0,
    y: 0.31,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      'trees/TEMPERATE_THIN_TREE_G1': 1,
      'trees/TEMPERATE_THIN_TREE_G2': 1,
      'trees/TEMPERATE_THIN_TREE_G3': 1,
      'trees/TEMPERATE_THIN_TREE_G4': 1,
      'trees/TEMPERATE_THIN_TREE_G5': 1,
      'trees/TEMPERATE_THIN_TREE_G6': 1,
      'trees/TEMPERATE_LARGE_TREE_G1': 3,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      void: 60,
    },
  },
  Cliff_start_1: {
    x: 0.2,
    y: 0.31,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      'trees/TEMPERATE_THIN_TREE_G1': 1,
      'trees/TEMPERATE_THIN_TREE_G2': 1,
      'trees/TEMPERATE_THIN_TREE_G3': 1,
      'trees/TEMPERATE_THIN_TREE_G4': 1,
      'trees/TEMPERATE_THIN_TREE_G5': 1,
      'trees/TEMPERATE_THIN_TREE_G6': 1,
      'trees/TEMPERATE_LARGE_TREE_G1': 3,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      void: 60,
    },
  },
  Cliff_up_1: {
    x: 0.25,
    y: 0.34,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      'trees/TEMPERATE_THIN_TREE_G1': 1,
      'trees/TEMPERATE_THIN_TREE_G2': 1,
      'trees/TEMPERATE_THIN_TREE_G3': 1,
      'trees/TEMPERATE_THIN_TREE_G4': 1,
      'trees/TEMPERATE_THIN_TREE_G5': 1,
      'trees/TEMPERATE_THIN_TREE_G6': 1,
      'trees/TEMPERATE_LARGE_TREE_G1': 3,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      void: 60,
    },
  },
  Cliff_down_1: {
    x: 0.35,
    y: 0.31,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      'trees/TEMPERATE_LARGE_TREE_G1': 3,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      void: 30,
    },
  },
  Valley: {
    x: 0.4,
    y: 0.31,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      'trees/TEMPERATE_LARGE_TREE_G1': 3,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      void: 30,
    },
  },
  Cliff_start_2: {
    x: 0.47,
    y: 0.31,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      'trees/TEMPERATE_THIN_TREE_G1': 1,
      'trees/TEMPERATE_THIN_TREE_G2': 1,
      'trees/TEMPERATE_THIN_TREE_G3': 1,
      'trees/TEMPERATE_THIN_TREE_G4': 1,
      'trees/TEMPERATE_THIN_TREE_G5': 1,
      'trees/TEMPERATE_THIN_TREE_G6': 1,
      'trees/TEMPERATE_LARGE_TREE_G1': 4,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      void: 20,
    },
  },
  Cliff_up_2: {
    x: 0.63,
    y: 0.5,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      'trees/TEMPERATE_THIN_TREE_G1': 1,
      'trees/TEMPERATE_THIN_TREE_G2': 1,
      'trees/TEMPERATE_THIN_TREE_G3': 1,
      'trees/TEMPERATE_THIN_TREE_G4': 1,
      'trees/TEMPERATE_THIN_TREE_G5': 1,
      'trees/TEMPERATE_THIN_TREE_G6': 1,
      'trees/TEMPERATE_LARGE_TREE_G1': 3,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      void: 20,
    },
  },
  Cliff_start_3: {
    x: 0.85,
    y: 0.52,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      void: 20,
    },
  },
  STONE: {
    x: 0.88,
    y: 0.6,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      void: 20,
    },
  },
  Cliff_up_3: {
    x: 0.9,
    y: 0.7,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      'rocks/TEMPERATE_ROCK_G3': 1,
      'rocks/TEMPERATE_ROCK_G4': 1,
      'rocks/TEMPERATE_ROCK_G5': 1,
      'rocks/TEMPERATE_ROCK_G6': 1,
      void: 20,
    },
  },
}
