import { BLOCKS } from '../blocks.js'

export default {
  1: {
    x: 0,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  2: {
    x: 0.01,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  3: {
    x: 0.03,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  4: {
    x: 0.05,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  5: {
    x: 0.07,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  6: {
    x: 0.09,
    y: 0.36,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  7: {
    x: 0.1,
    y: 0.43,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  8: {
    x: 0.11,
    y: 0.48,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  9: {
    x: 0.12,
    y: 0.55,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  10: {
    x: 0.13,
    y: 0.61,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  11: {
    x: 0.14,
    y: 0.63,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  12: {
    x: 0.15,
    y: 0.66,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  13: {
    x: 0.16,
    y: 0.68,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  14: {
    x: 0.17,
    y: 0.71,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  15: {
    x: 0.2,
    y: 0.73,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  16: {
    x: 0.23,
    y: 0.73,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  17: {
    x: 0.26,
    y: 0.71,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  18: {
    x: 0.27,
    y: 0.69,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  19: {
    x: 0.28,
    y: 0.64,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  20: {
    x: 0.29,
    y: 0.6,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  21: {
    x: 0.3,
    y: 0.57,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  22: {
    x: 0.31,
    y: 0.53,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  23: {
    x: 0.32,
    y: 0.51,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  24: {
    x: 0.33,
    y: 0.46,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  25: {
    x: 0.34,
    y: 0.43,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  26: {
    x: 0.35,
    y: 0.38,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  27: {
    x: 0.36,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  28: {
    x: 0.37,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  29: {
    x: 0.39,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  30: {
    x: 0.42,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  31: {
    x: 0.45,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  32: {
    x: 0.47,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  33: {
    x: 0.5,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  34: {
    x: 0.53,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  35: {
    x: 0.55,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  36: {
    x: 0.56,
    y: 0.38,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  37: {
    x: 0.57,
    y: 0.39,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  38: {
    x: 0.58,
    y: 0.42,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  39: {
    x: 0.59,
    y: 0.44,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  40: {
    x: 0.6,
    y: 0.45,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  41: {
    x: 0.61,
    y: 0.48,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  42: {
    x: 0.62,
    y: 0.5,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  43: {
    x: 0.63,
    y: 0.53,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  44: {
    x: 0.64,
    y: 0.57,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  45: {
    x: 0.65,
    y: 0.59,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  46: {
    x: 0.66,
    y: 0.65,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  47: {
    x: 0.67,
    y: 0.69,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  48: {
    x: 0.68,
    y: 0.73,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  49: {
    x: 0.69,
    y: 0.76,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  50: {
    x: 0.72,
    y: 0.78,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  51: {
    x: 0.75,
    y: 0.78,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  52: {
    x: 0.78,
    y: 0.76,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  53: {
    x: 0.79,
    y: 0.73,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  54: {
    x: 0.8,
    y: 0.69,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  55: {
    x: 0.81,
    y: 0.65,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  56: {
    x: 0.82,
    y: 0.59,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  57: {
    x: 0.83,
    y: 0.57,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  58: {
    x: 0.84,
    y: 0.53,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  59: {
    x: 0.85,
    y: 0.5,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TEMPERATE_ROCK_G1': 3,
      'rocks/TEMPERATE_ROCK_G2': 3,
      'rocks/TEMPERATE_ROCK_G3': 3,
      'rocks/TEMPERATE_ROCK_G4': 3,
      'rocks/TEMPERATE_ROCK_G5': 3,
      'rocks/TEMPERATE_ROCK_G6': 3,
      void: 20,
    },
  },
  60: {
    x: 0.86,
    y: 0.48,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  61: {
    x: 0.87,
    y: 0.45,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  62: {
    x: 0.88,
    y: 0.44,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  63: {
    x: 0.89,
    y: 0.42,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  64: {
    x: 0.9,
    y: 0.39,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  65: {
    x: 0.91,
    y: 0.38,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  66: {
    x: 0.92,
    y: 0.355,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  67: {
    x: 0.94,
    y: 0.34,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  68: {
    x: 0.96,
    y: 0.35,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  69: {
    x: 0.99,
    y: 0.34,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TEMPERATE_THIN_TREE_G1': 3,
      'trees/TEMPERATE_THIN_TREE_G2': 3,
      'trees/TEMPERATE_THIN_TREE_G3': 3,
      'trees/TEMPERATE_THIN_TREE_G4': 3,
      'trees/TEMPERATE_THIN_TREE_G5': 3,
      'trees/TEMPERATE_THIN_TREE_G6': 3,
      'trees/TEMPERATE_LARGE_TREE_G1': 1,
      'trees/TEMPERATE_LARGE_TREE_G2': 1,
      'trees/TEMPERATE_LARGE_TREE_G3': 1,
      'rocks/TEMPERATE_ROCK_G1': 1,
      'rocks/TEMPERATE_ROCK_G2': 1,
      void: 20,
    },
  },
  70: {
    x: 1,
    y: 0.34,
    type: BLOCKS.GRASS_TEMPERATE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
}
