import { BLOCKS } from '../blocks.js'

export default {
  1: {
    x: 0,
    y: 0.25,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  2: {
    x: 0.07,
    y: 0.27,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  3: {
    x: 0.1,
    y: 0.27,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  4: {
    x: 0.14,
    y: 0.28,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
  },
  5: {
    x: 0.18,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 2,
      'trees/TROPICAL_NORMAL_TREE_G2': 2,
      'trees/TROPICAL_NORMAL_TREE_G3': 2,
      'trees/TROPICAL_NORMAL_TREE_G4': 2,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      'rocks/TROPICAL_BIG_ROCK_G1': 1,
      'rocks/TROPICAL_BIG_ROCK_G2': 1,
      'rocks/TROPICAL_BIG_ROCK_G3': 1,
      'rocks/TROPICAL_BIG_ROCK_G4': 1,
      void: 10,
    },
  },
  6: {
    x: 0.22,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 2,
      'trees/TROPICAL_NORMAL_TREE_G2': 2,
      'trees/TROPICAL_NORMAL_TREE_G3': 2,
      'trees/TROPICAL_NORMAL_TREE_G4': 2,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      'rocks/TROPICAL_BIG_ROCK_G1': 1,
      'rocks/TROPICAL_BIG_ROCK_G2': 1,
      'rocks/TROPICAL_BIG_ROCK_G3': 1,
      'rocks/TROPICAL_BIG_ROCK_G4': 1,
      void: 10,
    },
  },
  7: {
    x: 0.3,
    y: 0.33,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G5': 3,
      'trees/TROPICAL_NORMAL_TREE_G6': 3,
      'trees/TROPICAL_NORMAL_TREE_G7': 3,
      'trees/TROPICAL_NORMAL_TREE_G8': 3,
      'trees/TROPICAL_NORMAL_TREE_G9': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      'rocks/TROPICAL_BIG_ROCK_G1': 2,
      'rocks/TROPICAL_BIG_ROCK_G2': 2,
      'rocks/TROPICAL_BIG_ROCK_G3': 2,
      'rocks/TROPICAL_BIG_ROCK_G4': 2,
      void: 5,
    },
  },
  8: {
    x: 0.34,
    y: 0.33,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G10': 3,
      'trees/TROPICAL_NORMAL_TREE_G11': 3,
      'trees/TROPICAL_NORMAL_TREE_G12': 3,
      'trees/TROPICAL_NORMAL_TREE_G13': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      'rocks/TROPICAL_BIG_ROCK_G1': 2,
      'rocks/TROPICAL_BIG_ROCK_G2': 2,
      'rocks/TROPICAL_BIG_ROCK_G3': 2,
      'rocks/TROPICAL_BIG_ROCK_G4': 2,
      void: 5,
    },
  },
  9: {
    x: 0.36,
    y: 0.34,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  10: {
    x: 0.37,
    y: 0.42,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  11: {
    x: 0.38,
    y: 0.52,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  12: {
    x: 0.39,
    y: 0.57,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  13: {
    x: 0.4,
    y: 0.66,
    type: BLOCKS.GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  14: {
    x: 0.42,
    y: 0.7,
    type: BLOCKS.GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  15: {
    x: 0.43,
    y: 0.71,
    type: BLOCKS.GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  16: {
    x: 0.44,
    y: 0.7,
    type: BLOCKS.GRASS,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  17: {
    x: 0.45,
    y: 0.66,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  18: {
    x: 0.46,
    y: 0.62,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  19: {
    x: 0.47,
    y: 0.56,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  20: {
    x: 0.48,
    y: 0.47,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  21: {
    x: 0.49,
    y: 0.42,
    type: BLOCKS.STONE,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  22: {
    x: 0.5,
    y: 0.36,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G10': 3,
      'trees/TROPICAL_NORMAL_TREE_G11': 3,
      'trees/TROPICAL_NORMAL_TREE_G12': 3,
      'trees/TROPICAL_NORMAL_TREE_G13': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      'rocks/TROPICAL_BIG_ROCK_G1': 2,
      'rocks/TROPICAL_BIG_ROCK_G2': 2,
      'rocks/TROPICAL_BIG_ROCK_G3': 2,
      'rocks/TROPICAL_BIG_ROCK_G4': 2,
      void: 5,
    },
  },
  23: {
    x: 0.51,
    y: 0.34,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G5': 3,
      'trees/TROPICAL_NORMAL_TREE_G6': 3,
      'trees/TROPICAL_NORMAL_TREE_G7': 3,
      'trees/TROPICAL_NORMAL_TREE_G8': 3,
      'trees/TROPICAL_NORMAL_TREE_G9': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      'rocks/TROPICAL_BIG_ROCK_G1': 2,
      'rocks/TROPICAL_BIG_ROCK_G2': 2,
      'rocks/TROPICAL_BIG_ROCK_G3': 2,
      'rocks/TROPICAL_BIG_ROCK_G4': 2,
      void: 5,
    },
  },
  24: {
    x: 0.53,
    y: 0.33,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 2,
      'trees/TROPICAL_NORMAL_TREE_G2': 2,
      'trees/TROPICAL_NORMAL_TREE_G3': 2,
      'trees/TROPICAL_NORMAL_TREE_G4': 2,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      'rocks/TROPICAL_BIG_ROCK_G1': 1,
      'rocks/TROPICAL_BIG_ROCK_G2': 1,
      'rocks/TROPICAL_BIG_ROCK_G3': 1,
      'rocks/TROPICAL_BIG_ROCK_G4': 1,
      void: 20,
    },
  },
  25: {
    x: 0.63,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 2,
      'trees/TROPICAL_NORMAL_TREE_G2': 2,
      'trees/TROPICAL_NORMAL_TREE_G3': 2,
      'trees/TROPICAL_NORMAL_TREE_G4': 2,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 10,
    },
  },
  26: {
    x: 0.76,
    y: 0.31,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
  },
  27: {
    x: 0.79,
    y: 0.29,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  28: {
    x: 0.87,
    y: 0.27,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  29: {
    x: 0.93,
    y: 0.26,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  30: {
    x: 0.97,
    y: 0.24,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  31: {
    x: 1,
    y: 0.22,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 0,
    fadeOut: 0,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
}
