import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  1: {
    x: 0,
    y: 0.22,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  2: {
    x: 0.09,
    y: 0.24,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 10,
      'rocks/TROPICAL_CORAIL_G2': 10,
      'rocks/TROPICAL_CORAIL_G3': 10,
      'rocks/TROPICAL_CORAIL_G4': 10,
      'rocks/TROPICAL_CORAIL_G5': 10,
      'rocks/TROPICAL_CORAIL_G6': 10,
      void: 20,
    },
  },
  3: {
    x: 0.13,
    y: 0.27,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      void: 20,
    },
  },
  4: {
    x: 0.17,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 20,
    },
  },
  5: {
    x: 0.19,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 20,
    },
  },
  6: {
    x: 0.22,
    y: 0.32,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G5': 3,
      'trees/TROPICAL_NORMAL_TREE_G6': 3,
      'trees/TROPICAL_NORMAL_TREE_G7': 3,
      'trees/TROPICAL_NORMAL_TREE_G8': 3,
      'trees/TROPICAL_NORMAL_TREE_G9': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 10,
    },
  },
  7: {
    x: 0.31,
    y: 0.33,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G10': 3,
      'trees/TROPICAL_NORMAL_TREE_G11': 3,
      'trees/TROPICAL_NORMAL_TREE_G12': 3,
      'trees/TROPICAL_NORMAL_TREE_G13': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 10,
    },
  },
  8: {
    x: 0.4,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 20,
    },
  },
  9: {
    x: 0.43,
    y: 0.31,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
  },
  10: {
    x: 0.46,
    y: 0.3,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
  },
  11: {
    x: 0.52,
    y: 0.3,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
  },
  12: {
    x: 0.55,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 20,
    },
  },
  13: {
    x: 0.58,
    y: 0.32,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G5': 3,
      'trees/TROPICAL_NORMAL_TREE_G6': 3,
      'trees/TROPICAL_NORMAL_TREE_G7': 3,
      'trees/TROPICAL_NORMAL_TREE_G8': 3,
      'trees/TROPICAL_NORMAL_TREE_G9': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 10,
    },
  },
  14: {
    x: 0.66,
    y: 0.33,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G10': 3,
      'trees/TROPICAL_NORMAL_TREE_G11': 3,
      'trees/TROPICAL_NORMAL_TREE_G12': 3,
      'trees/TROPICAL_NORMAL_TREE_G13': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 10,
    },
  },
  15: {
    x: 0.74,
    y: 0.33,
    type: BLOCKS.GOLDEN_SAND,
    subtype: BLOCKS.GOLDEN_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G5': 3,
      'trees/TROPICAL_NORMAL_TREE_G6': 3,
      'trees/TROPICAL_NORMAL_TREE_G7': 3,
      'trees/TROPICAL_NORMAL_TREE_G8': 3,
      'trees/TROPICAL_NORMAL_TREE_G9': 3,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 10,
    },
  },
  16: {
    x: 0.81,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 20,
    },
  },
  17: {
    x: 0.87,
    y: 0.32,
    type: BLOCKS.SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/DESERT_TREE_G1': 1,
      'trees/DESERT_TREE_G2': 1,
      'trees/DESERT_TREE_G3': 1,
      'trees/DESERT_TREE_G4': 1,
      'trees/DESERT_TREE_G5': 1,
      'trees/DESERT_TREE_G6': 1,
      void: 20,
    },
  },
  18: {
    x: 0.89,
    y: 0.315,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
  },
  19: {
    x: 0.91,
    y: 0.31,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 1,
      'rocks/TROPICAL_CORAIL_G2': 1,
      'rocks/TROPICAL_CORAIL_G3': 1,
      'rocks/TROPICAL_CORAIL_G4': 1,
      'rocks/TROPICAL_CORAIL_G5': 1,
      'rocks/TROPICAL_CORAIL_G6': 1,
      void: 20,
    },
  },
  20: {
    x: 0.96,
    y: 0.27,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 1,
      'rocks/TROPICAL_CORAIL_G2': 1,
      'rocks/TROPICAL_CORAIL_G3': 1,
      'rocks/TROPICAL_CORAIL_G4': 1,
      'rocks/TROPICAL_CORAIL_G5': 1,
      'rocks/TROPICAL_CORAIL_G6': 1,
      void: 20,
    },
  },
  21: {
    x: 1,
    y: 0.26,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'rocks/TROPICAL_CORAIL_G1': 1,
      'rocks/TROPICAL_CORAIL_G2': 1,
      'rocks/TROPICAL_CORAIL_G3': 1,
      'rocks/TROPICAL_CORAIL_G4': 1,
      'rocks/TROPICAL_CORAIL_G5': 1,
      'rocks/TROPICAL_CORAIL_G6': 1,
      void: 20,
    },
  },
}
