import { BlockType } from '@aresrpg/aresrpg-world'

import { BLOCKS } from '../blocks.js'

export default {
  Water: {
    x: 0,
    y: 0,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.WET_SAND,
    fadeIn: 5,
    fadeOut: 5,
  },
  Rive_Mud_up: {
    x: 0.1,
    y: 0.1,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.SAND,
    fadeIn: 5,
    fadeOut: 5,
    flora: {},
  },
  Plateau_up: {
    x: 0.15,
    y: 0.305,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Plateau_down_1: {
    x: 0.2,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Rive_Mud_down_1: {
    x: 0.25,
    y: 0.305,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Water_1: {
    x: 0.4,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BlockType.NONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  Rive_Mud_up_1: {
    x: 0.45,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Plateau_up_1: {
    x: 0.47,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Plateau_down_2: {
    x: 0.52,
    y: 0.315,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Rive_Mud_down_2: {
    x: 0.57,
    y: 0.31,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Water_2: {
    x: 0.7,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BlockType.NONE,
    fadeIn: 5,
    fadeOut: 5,
  },
  Rive_Mud_up_2: {
    x: 0.75,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Plateau_up_2: {
    x: 0.77,
    y: 0.31,
    type: BLOCKS.WET_SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
  Water_3: {
    x: 0.85,
    y: 0.3,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {},
  },
  Plateau: {
    x: 0.92,
    y: 0.31,
    type: BLOCKS.SAND,
    subtype: BLOCKS.STONE,
    fadeIn: 5,
    fadeOut: 5,
    flora: {
      'trees/TROPICAL_NORMAL_TREE_G1': 1,
      'trees/TROPICAL_NORMAL_TREE_G2': 1,
      'trees/TROPICAL_NORMAL_TREE_G3': 1,
      'trees/TROPICAL_NORMAL_TREE_G4': 1,
      'trees/TROPICAL_NORMAL_TREE_G5': 1,
      'trees/TROPICAL_NORMAL_TREE_G6': 1,
      'trees/TROPICAL_NORMAL_TREE_G7': 1,
      'trees/TROPICAL_NORMAL_TREE_G8': 1,
      'trees/TROPICAL_NORMAL_TREE_G9': 1,
      'trees/TROPICAL_NORMAL_TREE_G10': 1,
      'trees/TROPICAL_NORMAL_TREE_G11': 1,
      'trees/TROPICAL_NORMAL_TREE_G12': 1,
      void: 10,
    },
  },
}
